[package]
name = "pairing_api"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
chacha20poly1305 = "0.9.1"
hex = "0.4.2"
hkdf = "0.12.4"
lazy_static = "1.4"
regex = "1.10.6"
thiserror = "1.0"
url = "2.3"
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
