[package]
name = "pairing_api"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.2"
lazy_static = "1.4"
paste = "1.0.15"
regex = "1.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "1.0"
url = "2.3"
