name: "kdf"

on:
  push:
    branches: ["kdf"]
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
